### ISSUE TITLE
Azure Deployment?

### ISSUE THREAD

**Issue by clebron949** [khalidabuhakmeh/TailwindAspNetCore#2]
Hi @khalidabuhakmeh,

I read your article and it was great!  Any recommendation on how to deploy this? Will it work with an Azure Web Service App? Or another Azure service?

Thanks!
Chris

**Comment by khalidabuhakmeh** [comment]
👋 Hi @clebron949.

This deployment should be straightforward, similar to any other ASP.NET Core web application. I would recommend Azure Web Apps, but you could also use Azure CDN to host the built static assets.

Cheers,

Khalid
